- job:
   name: create-git-repo
   parameters:
     - string:
         name: 'SERVICE_NAME'
         description: 'Name of the new microservice'
         default: 'example-service'
     - password:
         name: 'OAUTH_TOKEN'
         description: 'Github OAUTH token'
         regex: '^[a-z]([a-z]|[0-9]|[-|_|\.])+$'
         msg: 'Invalid token'
   logrotate:
     daysToKeep: 1
     numToKeep: 3
     artifactDaysToKeep: -1
     artifactNumToKeep: -1
   properties:
     - delivery-pipeline:
         stage: Source control
         task: 'Create git repository'
     - build-blocker:
         use-build-blocker: true
         blocking-jobs:
           - "create-git-repo"
   wrappers:
     - timestamps
     - workspace-cleanup
     - inject-passwords:
         mask-password-params: true
   builders:
     - shell: |
          set -e
          echo "Creating git repository"
          # For organizations, use /orgs/:org/repos instead of /user/repos
          curl -X POST -H "Authorization: token $OAUTH_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/repos -d "{ \"name\": \"$SERVICE_NAME\" }"
          echo "Successfully created git repository"
