- job:
   name: create-git-repo
   parameters:
     - string:
         name: 'SERVICE_NAME'
         description: 'Name of the new microservice'
         default: 'example-service'
     - password:
         name: 'OAUTH_TOKEN'
         description: 'Github OAUTH token'
         regex: '^[a-z]([a-z]|[0-9]|[-|_|\.])+$'
         msg: 'Invalid token'
     - string:
         name: 'JOB_CONFIG_PATH'
         description: 'Path to Jenkins Job Builder job configuration templates'
         default: '/etc/jenkins_jobs'
   build-discarder:
     daysToKeep: 1
     numToKeep: 3
     artifactDaysToKeep: -1
     artifactNumToKeep: -1
   properties:
     - delivery-pipeline:
         stage: Setup infrastructure
         task: 'Create git repository'
     - build-blocker:
         use-build-blocker: true
         blocking-jobs:
           - "create-git-repo"
   wrappers:
     - timestamps
     - workspace-cleanup
     - inject-passwords:
         mask-password-params: true
   builders:
     - shell: |
        #!/bin/bash
        set -e
        echo "Creating git repository"
        # For organizations, use /orgs/:org/repos instead of /user/repos
        RES=$(curl -X POST -H "Authorization: token $OAUTH_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/repos -d "{ \"name\": \"$SERVICE_NAME\" }")
        echo $RES
        GIT_URL=$(echo "$RES" | python -m json.tool | grep clone_url | awk '{ print $2 }' | sed 's/"//g' | sed 's/,//g')
        if [ -z $GIT_URL ]; then
             echo "Failed to create git repo"
             exit 1
        fi
        git config --global user.email "jenkins@jenkins.com"
        git config --global user.name "Jenkins"
        echo "Successfully created git repository: $GIT_URL"
        APPLICATION_NAME=${SERVICE_NAME%-*}
        mvn archetype:generate -DarchetypeGroupId=io.dropwizard.archetypes -DarchetypeArtifactId=java-simple -DarchetypeVersion=1.0.1 -DgroupId=com.example -DartifactId=$SERVICE_NAME -Dversion=0.0.1 -Dname=$APPLICATION_NAME -DinteractiveMode=false
        cd $SERVICE_NAME
        git init .
        git add --all
        git commit -m "Initial commit"
        ORIGIN=$(echo ${GIT_URL} | sed "s;github.com;${OAUTH_TOKEN}@github.com;g")
        git remote add origin $ORIGIN
        git push origin master
        echo "Generate pipeline for $SERVICE_NAME"
        cat ${JOB_CONFIG_PATH}/service-pipeline-job-configurations.yml.template | sed "s;{service-name};${SERVICE_NAME};g" | sed "s;{git-url};${GIT_URL};g" > ${JOB_CONFIG_PATH}/${SERVICE_NAME}-pipeline-job-configurations.yml
        jenkins-jobs update ${JOB_CONFIG_PATH}/${SERVICE_NAME}-pipeline-job-configurations.yml
